### PR TITLE
Jakkula

### PR DESCRIPTION
**Pull request by Jakkula-Gayathri**
Hey Parth!
Review my files and leave your valuable comments.

Thanks!

### CODE REVIEW

**Comment by SiddharthMurjani** [comment]
Hi Jakkula,

You have to do the following changes
1. You have not followed the branch naming convention. Rectify it.
2. You have not added files to the src folder.
3. You have used `git add .` to stage all the files, there is a file `.DS_Store` that should not be a part of your pr. Rectify it.

**Comment by Jakkula-Gayathri** [comment]
Hi Siddharth,
I will update the Changes .
Thanks for the review!

**Comment by Jakkula-Gayathri** [comment]
Siddharth ,

I changed branch name in local repo after that I used push , but in remote repo two branches are there as shown in image   . 🤔.Do I need to create new pull request for renamed branch.
Screenshot 2023-05-28 at 3 34 54 PM

Screenshot 2023-05-28 at 3 46 55 PM

**Comment by SiddharthMurjani** [comment]
Yes, Gayatri, you need to create a new pull request and delete the old branch from GitHub.

Also, from what I can see, you still have `.DS_Store` file in your pr, also whatever work you are doing, that has to be in the `src` folder as instructed.

If you are not sure how to get rid of the `.DS_Store` file, go ahead and read about `.gitignore`.

**Pull request closed without merging**
